# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-26 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DtcSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_data', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'DTC Snapshot',
            },
        ),
        migrations.CreateModel(
            name='Ecu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('acronym', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'ECU',
                'verbose_name_plural': 'ECU',
            },
        ),
        migrations.CreateModel(
            name='EcuRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sent_bytes', models.CharField(max_length=255)),
                ('received_minbytes', models.IntegerField()),
                ('received_bytes', models.CharField(max_length=255)),
                ('received_data_name', models.CharField(blank=True, max_length=255, null=True)),
                ('received_data_first_byte', models.IntegerField(blank=True, null=True)),
                ('received_data_bit_offset', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ECU Request',
            },
        ),
        migrations.CreateModel(
            name='EcuSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(blank=True, max_length=15, null=True)),
                ('part_reference', models.CharField(blank=True, max_length=10, null=True)),
                ('hardware_reference', models.CharField(blank=True, max_length=10, null=True)),
                ('calibration_reference', models.CharField(blank=True, max_length=10, null=True)),
                ('software_reference', models.CharField(blank=True, max_length=10, null=True)),
                ('supplier', models.CharField(blank=True, max_length=200, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=200, null=True)),
                ('diag_version', models.CharField(blank=True, max_length=15, null=True)),
                ('ecu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporter.Ecu')),
            ],
            options={
                'verbose_name': 'ECU Snapshot',
            },
        ),
        migrations.CreateModel(
            name='TrwFailsafeMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='static/uploads/supplier/trw/failsafe/')),
                ('ecu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.Ecu')),
            ],
            options={
                'verbose_name': 'TRW Failsafe Matrix',
                'verbose_name_plural': 'TRW Failsafe Matrices',
            },
        ),
        migrations.CreateModel(
            name='UdsDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='static/uploads/ddt2000/ecus/')),
                ('version', models.CharField(editable=False, max_length=255)),
                ('supplier', models.CharField(editable=False, max_length=255)),
                ('ecu', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='reporter.Ecu')),
            ],
            options={
                'verbose_name': 'UDS Database',
            },
        ),
        migrations.CreateModel(
            name='UdsDatabaseDefinitionEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('text', models.CharField(max_length=255)),
                ('database', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reporter.UdsDatabase')),
            ],
        ),
        migrations.CreateModel(
            name='UdsDatabaseObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'UDS Database Entry Type',
            },
        ),
        migrations.CreateModel(
            name='UdsDatabaseValueEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.DtcSnapshot')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reporter.UdsDatabaseObjectType')),
            ],
            options={
                'verbose_name': 'UDS Database Entry',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vin', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('production_date', models.DateTimeField(blank=True, null=True)),
                ('sale_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=25, null=True)),
                ('model', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='static/uploads/snapshots/')),
                ('captured_on', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='reporter.Vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Snapshot',
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporter.VehicleModel'),
        ),
        migrations.AddField(
            model_name='udsdatabasedefinitionentry',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reporter.UdsDatabaseObjectType'),
        ),
        migrations.AddField(
            model_name='ecusnapshot',
            name='uds_database',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporter.UdsDatabase'),
        ),
        migrations.AddField(
            model_name='ecusnapshot',
            name='vehicle_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.VehicleSnapshot'),
        ),
        migrations.AddField(
            model_name='ecurequest',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.UdsDatabase'),
        ),
        migrations.AddField(
            model_name='dtcsnapshot',
            name='confirmed_dtc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_dtcsnapshot_dtc_set', to='reporter.UdsDatabaseValueEntry'),
        ),
        migrations.AddField(
            model_name='dtcsnapshot',
            name='device_identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_identifier_dtcsnapshot_set', to='reporter.UdsDatabaseValueEntry'),
        ),
        migrations.AddField(
            model_name='dtcsnapshot',
            name='ecu_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.EcuSnapshot'),
        ),
        migrations.AddField(
            model_name='dtcsnapshot',
            name='event_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_status_dtcsnapshot_set', to='reporter.UdsDatabaseValueEntry'),
        ),
        migrations.AddField(
            model_name='dtcsnapshot',
            name='extended_data_record_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extended_data_record_number_dtcsnapshot_set', to='reporter.UdsDatabaseValueEntry'),
        ),
        migrations.AddField(
            model_name='dtcsnapshot',
            name='failure_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='failure_type_dtcsnapshot_set', to='reporter.UdsDatabaseValueEntry'),
        ),
        migrations.AddField(
            model_name='dtcsnapshot',
            name='failure_type_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='failure_type_category_dtcsnapshot_set', to='reporter.UdsDatabaseValueEntry'),
        ),
        migrations.AddField(
            model_name='dtcsnapshot',
            name='format_identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='format_identifier_dtcsnapshot_set', to='reporter.UdsDatabaseValueEntry'),
        ),
        migrations.AddField(
            model_name='dtcsnapshot',
            name='pending_dtc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pending_dtcsnapshot_dtc_set', to='reporter.UdsDatabaseValueEntry'),
        ),
        migrations.AddField(
            model_name='dtcsnapshot',
            name='test_failed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_failed_dtcsnapshot_set', to='reporter.UdsDatabaseValueEntry'),
        ),
        migrations.AddField(
            model_name='dtcsnapshot',
            name='test_failed_since_last_clear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_failed_since_last_clear_dtcsnapshot_set', to='reporter.UdsDatabaseValueEntry'),
        ),
        migrations.AddField(
            model_name='dtcsnapshot',
            name='test_failed_this_monitoring_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_failed_this_monitoring_cycle_dtcsnapshot_set', to='reporter.UdsDatabaseValueEntry'),
        ),
        migrations.AddField(
            model_name='dtcsnapshot',
            name='test_not_completed_since_last_clear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_not_completed_since_last_clear_dtcsnapshot_set', to='reporter.UdsDatabaseValueEntry'),
        ),
        migrations.AddField(
            model_name='dtcsnapshot',
            name='test_not_completed_this_monitoring_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_not_completed_this_monitoring_cycle_dtcsnapshot_set', to='reporter.UdsDatabaseValueEntry'),
        ),
        migrations.AddField(
            model_name='dtcsnapshot',
            name='warning_indicator_requested',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warning_indicator_requested_dtcsnapshot_set', to='reporter.UdsDatabaseValueEntry'),
        ),
        migrations.AlterUniqueTogether(
            name='vehiclesnapshot',
            unique_together=set([('vehicle', 'captured_on')]),
        ),
        migrations.AlterUniqueTogether(
            name='udsdatabase',
            unique_together=set([('ecu', 'version')]),
        ),
        migrations.AlterUniqueTogether(
            name='ecusnapshot',
            unique_together=set([('vehicle_snapshot', 'ecu')]),
        ),
    ]
