# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-26 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dtcsnapshot',
            name='confirmed_dtc',
        ),
        migrations.RemoveField(
            model_name='dtcsnapshot',
            name='device_identifier',
        ),
        migrations.RemoveField(
            model_name='dtcsnapshot',
            name='event_status',
        ),
        migrations.RemoveField(
            model_name='dtcsnapshot',
            name='extended_data_record_number',
        ),
        migrations.RemoveField(
            model_name='dtcsnapshot',
            name='failure_type',
        ),
        migrations.RemoveField(
            model_name='dtcsnapshot',
            name='failure_type_category',
        ),
        migrations.RemoveField(
            model_name='dtcsnapshot',
            name='format_identifier',
        ),
        migrations.RemoveField(
            model_name='dtcsnapshot',
            name='pending_dtc',
        ),
        migrations.RemoveField(
            model_name='dtcsnapshot',
            name='test_failed',
        ),
        migrations.RemoveField(
            model_name='dtcsnapshot',
            name='test_failed_since_last_clear',
        ),
        migrations.RemoveField(
            model_name='dtcsnapshot',
            name='test_failed_this_monitoring_cycle',
        ),
        migrations.RemoveField(
            model_name='dtcsnapshot',
            name='test_not_completed_since_last_clear',
        ),
        migrations.RemoveField(
            model_name='dtcsnapshot',
            name='test_not_completed_this_monitoring_cycle',
        ),
        migrations.RemoveField(
            model_name='dtcsnapshot',
            name='warning_indicator_requested',
        ),
    ]
