# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-26 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_auto_20161026_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='udsdatabasedefinitionentry',
            options={'verbose_name': 'UDS Database Definition Entry', 'verbose_name_plural': 'UDS Database Definition Entries'},
        ),
        migrations.AlterModelOptions(
            name='udsdatabasevalueentry',
            options={'verbose_name': 'UDS Database Value Entry', 'verbose_name_plural': 'UDS Database Value Entries'},
        ),
        migrations.RenameField(
            model_name='udsdatabasevalueentry',
            old_name='parent',
            new_name='dtc_snapshot',
        ),
    ]
