# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-28 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0003_auto_20161026_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtcsnapshot',
            name='status_byte',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dtcsnapshot',
            name='status_byte_availabilty_mask',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
