# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-31 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0004_auto_20161028_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dtc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_identifier', models.CharField(max_length=255)),
                ('failure_type', models.CharField(max_length=255)),
                ('ecu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.Ecu')),
            ],
            options={
                'verbose_name': 'Diagnostic Trouble Code',
            },
        ),
        migrations.AlterModelOptions(
            name='udsdatabaseobjecttype',
            options={'verbose_name': 'UDS Database Object Type'},
        ),
        migrations.AddField(
            model_name='dtcsnapshot',
            name='dtc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reporter.Dtc'),
        ),
        migrations.AlterUniqueTogether(
            name='dtc',
            unique_together=set([('device_identifier', 'failure_type')]),
        ),
    ]
