# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-31 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0005_auto_20161031_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtc',
            name='device_identifier',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='dtc',
            name='failure_type',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
