# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-31 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0006_auto_20161031_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtc',
            name='device_identifier',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='dtc',
            name='failure_type',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='dtcsnapshot',
            name='status_byte',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dtcsnapshot',
            name='status_byte_availabilty_mask',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
