# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-07 00:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0007_auto_20161031_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='udsdatabase',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='udsdatabasedefinitionentry',
            name='database',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporter.UdsDatabase'),
        ),
        migrations.AlterField(
            model_name='udsdatabasedefinitionentry',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.UdsDatabaseObjectType'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='VIN Invalid', regex='^[A-Z0-9]+$')]),
        ),
    ]
