# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-07 06:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0008_auto_20161107_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecusnapshot',
            old_name='uds_database',
            new_name='_uds_database',
        ),
    ]
